language: go

go:
- '1.13'

script:
- go vet ./...
- make test

before_deploy: |
  if [  ! -f /tmp/tagged ]; then
    git config --local user.name "$USERNAME"
    git config --local user.email "$EMAIL"
    # Compile Binaries
    make release
    export TRAVIS_TAG=$(grep -o "[0-9]\.[0-9]\.[0-9]"  Makefile)
    export TRAVIS_ARTIFACT=$(ls *.tar.gz)
    # Tag
    git tag $TRAVIS_TAG && touch /tmp/tagged
    # Update go report card
    curl -X POST -F "repo=github.com/${TRAVIS_REPO_SLUG}" https://goreportcard.com/checks
  fi

deploy:
  provider: releases
  api_key:
    secure: mEMarcXKXNOBfVqd6W6ihT+8YOIgMd7S4R0YmgxLhxwG+JX5rUsQRXEjHDqpwb1nUrQNB57tWHuvFwCzw9cchfckf/38kHmjNLXjMzBuXXS5hk9wvyofbE39kROrRqLMx9v0pp3wk00wjZN5OwsGqGfKgO3SxthoK5aja3zrDT8sdc/TfZgVU25U4f5dK3MjNRxXxWBumgxhYg8Uv64CKlX2dzARUWH2SfZflgLIH6kk/Ab+xSAeZ0M+rld0tme1Teg1BDdCTVMe9/oc5N0esffPyFxou3x26NgctM992a3PtUfETq/vB6PZnDepFBPHn/gRUt2Tqf3bZlThmXT/5mAXBaK1AYHQWr19c+tnaSvqaGDVoG0yf5RPcMhz5soji+sECU/4Su1jYF6ASvziAoI1eU+2iaYv7bx1k4FLfp0dYuvBTzc3wPmrb0WPsuckU05M/Oe6zKTnpcfClaZoftS49PTBNufDXEyOPdxOU9WLlkTCmtq9Sk+SUKK+2xGUxr6qgT4VNiuLPCiflBrpOOLlD3Y//yX/W43wWqWtRXDQsgKJXN/OGUp3vZaciCm33b59cNT9zuDzzrktMAXMGAx8hdZY6og9WVg7gcuHoTF3pJYWq/cbt1/cW8LA8DjGDhFqxTxRgIWuJIfbmAGcET2GBZHDNODzo0Zd/ubnW0o=
  file: bin/*.*
  on:
    branch: master
